name: Setup Apache on EC2

on:
  push:
    branches: [ "main" ]

jobs:
  install-apache:
    runs-on: ubuntu-latest

    steps:
      - name: Install Apache on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo apt update
            sudo apt install -y apache2
            sudo systemctl enable --now apache2
          